[package]
name = "gitauthor-set-random"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
bstr = { version = "1.10", default-features = false, features = ["alloc"] }
clap = { version = "4.5.7", features = ["derive", "wrap_help"] }
rand = "0.8.5"
