[package]
name = "gitauthor-set-random"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
bstr = { version = "1.10", default-features = false, features = ["alloc"] }
cj-path-util = { version = "0.4.0", features = ["unix"] }
clap = { version = "4.5.7", features = ["derive", "wrap_help"] }
derive_more = { version = "2.0.1", features = ["from", "from_str"] }
rand = "0.8.5"
